name: zammacarsharing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^1.1.5
  intl_phone_field: ^3.1.0
  flutter_otp_text_field: ^1.1.1
  dotted_border: ^2.0.0+3
  google_maps_flutter: ^2.2.1
  get_storage: ^2.0.3
  intl: ^0.18.0
  flutter_credit_card: ^3.0.6
  camera: ^0.10.5+5
  path_provider: ^2.0.15
  url_launcher: ^6.0.0
  flutter_local_notifications: ^15.1.0+1
  firebase_messaging: ^14.6.4


  get: 4.6.5
  flutter: 
    sdk: flutter

  dio: ^5.2.1+1
  google_fonts: ^4.0.4
  encrypt: ^5.0.1
  tuple: ^2.0.1
  crypto: ^3.0.2
  firebase_auth: ^4.15.0
  flutter_facebook_auth: ^5.0.6
  sms_autodetect: ^1.0.9

  google_sign_in: ^5.4.2
  sign_in_with_apple: ^3.2.0
  twitter_login: ^4.2.3
  firebase_core: ^2.3.0
  rename: ^2.0.1
  jwt_decoder: ^2.0.1
  lottie: ^2.0.0
  cached_network_image: ^3.3.1
  shimmer: ^2.0.0
  image_picker: ^0.8.7+1
  geolocator: ^9.0.2
  flutter_launcher_icons: ^0.11.0
  loader_overlay: ^2.1.0
  qr_bar_code_scanner_dialog: ^0.0.5
  path: ^1.8.2
  geocoding: ^2.1.0
  pretty_dio_logger: ^1.3.1




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/