name: zammacarsharing
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  flutter_svg: ^1.1.5
  modal_bottom_sheet: ^2.1.2
  intl_phone_field: ^3.1.0
  flutter_otp_text_field: ^1.1.1
  dotted_border: ^2.0.0+3
  google_maps_flutter: ^2.2.1
  get_storage: ^2.0.3


  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^4.0.6
  google_fonts: ^3.0.1
  encrypt: ^5.0.1
  tuple: ^2.0.1
  crypto: ^3.0.2
  firebase_auth: ^4.1.4
  flutter_facebook_auth: ^5.0.6
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^3.2.0
  twitter_login: ^4.2.3
  firebase_core: ^2.3.0
  rename: ^2.0.1
  jwt_decoder: ^2.0.1
  lottie: ^2.0.0
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  image_picker: ^0.8.5+3
  geolocator: ^9.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/