///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BookingOngoingDataDropLocation {
/*
{
  "type": "Point",
  "coordinates": [
    83.37816239552401
  ]
}
*/

  String? type;
  List<double?>? coordinates;

  BookingOngoingDataDropLocation({
    this.type,
    this.coordinates,
  });
  BookingOngoingDataDropLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class BookingOngoingDataPickupLocation {
/*
{
  "type": "Point",
  "coordinates": [
    83.37816239552401
  ],
  "address": "Gorakhpur"
}
*/

  String? type;
  List<double?>? coordinates;
  String? address;

  BookingOngoingDataPickupLocation({
    this.type,
    this.coordinates,
    this.address,
  });
  BookingOngoingDataPickupLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['address'] = address;
    return data;
  }
}

class BookingOngoingData {
/*
{
  "pickupLocation": {
    "type": "Point",
    "coordinates": [
      83.37816239552401
    ],
    "address": "Gorakhpur"
  },
  "dropLocation": {
    "type": "Point",
    "coordinates": [
      83.37816239552401
    ]
  },
  "_id": "63a2e79b33e4a03b10a8a279",
  "user": "637b3573e25e4f6d1227a1de",
  "car": "637b37064bab010aa878e348",
  "status": "ongoing",
  "pickupTime": "2022-12-21T13:52:44.615Z",
  "dropTime": "",
  "cancelReason": "",
  "isPaymentSuccess": false,
  "paymentMethod": "",
  "isDeleted": false,
  "createdAt": "2022-12-21T11:01:47.874Z",
  "updatedAt": "2022-12-21T13:52:44.619Z"
}
*/

  BookingOngoingDataPickupLocation? pickupLocation;
  BookingOngoingDataDropLocation? dropLocation;
  String? Id;
  String? user;
  String? car;
  String? status;
  String? pickupTime;
  String? dropTime;
  String? cancelReason;
  bool? isPaymentSuccess;
  String? paymentMethod;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;

  BookingOngoingData({
    this.pickupLocation,
    this.dropLocation,
    this.Id,
    this.user,
    this.car,
    this.status,
    this.pickupTime,
    this.dropTime,
    this.cancelReason,
    this.isPaymentSuccess,
    this.paymentMethod,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
  });
  BookingOngoingData.fromJson(Map<String, dynamic> json) {
    pickupLocation = (json['pickupLocation'] != null) ? BookingOngoingDataPickupLocation.fromJson(json['pickupLocation']) : null;
    dropLocation = (json['dropLocation'] != null) ? BookingOngoingDataDropLocation.fromJson(json['dropLocation']) : null;
    Id = json['_id']?.toString();
    user = json['user']?.toString();
    car = json['car']?.toString();
    status = json['status']?.toString();
    pickupTime = json['pickupTime']?.toString();
    dropTime = json['dropTime']?.toString();
    cancelReason = json['cancelReason']?.toString();
    isPaymentSuccess = json['isPaymentSuccess'];
    paymentMethod = json['paymentMethod']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pickupLocation != null) {
      data['pickupLocation'] = pickupLocation!.toJson();
    }
    if (dropLocation != null) {
      data['dropLocation'] = dropLocation!.toJson();
    }
    data['_id'] = Id;
    data['user'] = user;
    data['car'] = car;
    data['status'] = status;
    data['pickupTime'] = pickupTime;
    data['dropTime'] = dropTime;
    data['cancelReason'] = cancelReason;
    data['isPaymentSuccess'] = isPaymentSuccess;
    data['paymentMethod'] = paymentMethod;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class BookingOngoing {
/*
{
  "status": true,
  "message": "Booking marked to ongoing",
  "data": {
    "pickupLocation": {
      "type": "Point",
      "coordinates": [
        83.37816239552401
      ],
      "address": "Gorakhpur"
    },
    "dropLocation": {
      "type": "Point",
      "coordinates": [
        83.37816239552401
      ]
    },
    "_id": "63a2e79b33e4a03b10a8a279",
    "user": "637b3573e25e4f6d1227a1de",
    "car": "637b37064bab010aa878e348",
    "status": "ongoing",
    "pickupTime": "2022-12-21T13:52:44.615Z",
    "dropTime": "",
    "cancelReason": "",
    "isPaymentSuccess": false,
    "paymentMethod": "",
    "isDeleted": false,
    "createdAt": "2022-12-21T11:01:47.874Z",
    "updatedAt": "2022-12-21T13:52:44.619Z"
  }
}
*/

  bool? status;
  String? message;
  BookingOngoingData? data;

  BookingOngoing({
    this.status,
    this.message,
    this.data,
  });
  BookingOngoing.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? BookingOngoingData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
