///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CarPriceByIdCarPricingMileageRates {
/*
{
  "miles": 121,
  "price": 11.01,
  "_id": "650d5c87231030773f368367"
}
*/

  int? miles;
  double? price;
  String? Id;

  CarPriceByIdCarPricingMileageRates({
    this.miles,
    this.price,
    this.Id,
  });
  CarPriceByIdCarPricingMileageRates.fromJson(Map<String, dynamic> json) {
    miles = json['miles']?.toInt();
    price = json['price']?.toDouble();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['miles'] = miles;
    data['price'] = price;
    data['_id'] = Id;
    return data;
  }
}

class CarPriceByIdCarPricingPricingRules {
/*
{
  "hours": 1,
  "price": 2.01,
  "_id": "650d59e1231030773f3682ed"
}
*/

  int? hours;
  double? price;
  String? Id;

  CarPriceByIdCarPricingPricingRules({
    this.hours,
    this.price,
    this.Id,
  });
  CarPriceByIdCarPricingPricingRules.fromJson(Map<String, dynamic> json) {
    hours = json['hours']?.toInt();
    price = json['price']?.toDouble();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['hours'] = hours;
    data['price'] = price;
    data['_id'] = Id;
    return data;
  }
}

class CarPriceByIdCarPricing {
/*
{
  "_id": "650b4b3a231030773f367a98",
  "car": "63f377e5d6cc2f883de290ce",
  "pricingRules": [
    {
      "hours": 1,
      "price": 2.01,
      "_id": "650d59e1231030773f3682ed"
    }
  ],
  "mileageRates": [
    {
      "miles": 121,
      "price": 11.01,
      "_id": "650d5c87231030773f368367"
    }
  ],
  "extraMinuteRate": 12.01,
  "extraMileRate": 1.01,
  "createdAt": "2023-09-20T19:42:50.583Z",
  "updatedAt": "2023-10-03T07:58:32.647Z"
}
*/

  String? Id;
  String? car;
  List<CarPriceByIdCarPricingPricingRules?>? pricingRules;
  List<CarPriceByIdCarPricingMileageRates?>? mileageRates;
  double? extraMinuteRate;
  double? extraMileRate;
  String? createdAt;
  String? updatedAt;

  CarPriceByIdCarPricing({
    this.Id,
    this.car,
    this.pricingRules,
    this.mileageRates,
    this.extraMinuteRate,
    this.extraMileRate,
    this.createdAt,
    this.updatedAt,
  });
  CarPriceByIdCarPricing.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    car = json['car']?.toString();
    if (json['pricingRules'] != null) {
      final v = json['pricingRules'];
      final arr0 = <CarPriceByIdCarPricingPricingRules>[];
      v.forEach((v) {
        arr0.add(CarPriceByIdCarPricingPricingRules.fromJson(v));
      });
      pricingRules = arr0;
    }
    if (json['mileageRates'] != null) {
      final v = json['mileageRates'];
      final arr0 = <CarPriceByIdCarPricingMileageRates>[];
      v.forEach((v) {
        arr0.add(CarPriceByIdCarPricingMileageRates.fromJson(v));
      });
      mileageRates = arr0;
    }
    extraMinuteRate = json['extraMinuteRate']?.toDouble();
    extraMileRate = json['extraMileRate']?.toDouble();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['car'] = car;
    if (pricingRules != null) {
      final v = pricingRules;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['pricingRules'] = arr0;
    }
    if (mileageRates != null) {
      final v = mileageRates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['mileageRates'] = arr0;
    }
    data['extraMinuteRate'] = extraMinuteRate;
    data['extraMileRate'] = extraMileRate;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class CarPriceById {
/*
{
  "status": true,
  "message": "Get car pricing by car Id",
  "carPricing": {
    "_id": "650b4b3a231030773f367a98",
    "car": "63f377e5d6cc2f883de290ce",
    "pricingRules": [
      {
        "hours": 1,
        "price": 2.01,
        "_id": "650d59e1231030773f3682ed"
      }
    ],
    "mileageRates": [
      {
        "miles": 121,
        "price": 11.01,
        "_id": "650d5c87231030773f368367"
      }
    ],
    "extraMinuteRate": 12.01,
    "extraMileRate": 1.01,
    "createdAt": "2023-09-20T19:42:50.583Z",
    "updatedAt": "2023-10-03T07:58:32.647Z"
  }
}
*/

  bool? status;
  String? message;
  CarPriceByIdCarPricing? carPricing;

  CarPriceById({
    this.status,
    this.message,
    this.carPricing,
  });
  CarPriceById.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    carPricing = (json['carPricing'] != null) ? CarPriceByIdCarPricing.fromJson(json['carPricing']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (carPricing != null) {
      data['carPricing'] = carPricing!.toJson();
    }
    return data;
  }
}
