///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CategoriesModelsCategory {
/*
{
  "_id": "637efe36bcbb6bd45019f1f5",
  "name": "SUV"
}
*/

  String? Id;
  String? name;

  CategoriesModelsCategory({
    this.Id,
    this.name,
  });
  CategoriesModelsCategory.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    return data;
  }
}

class CategoriesModels {
/*
{
  "status": true,
  "message": "Get all category",
  "category": [
    {
      "_id": "637efe36bcbb6bd45019f1f5",
      "name": "SUV"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<CategoriesModelsCategory?>? category;

  CategoriesModels({
    this.status,
    this.message,
    this.category,
  });
  CategoriesModels.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['category'] != null) {
      final v = json['category'];
      final arr0 = <CategoriesModelsCategory>[];
      v.forEach((v) {
        arr0.add(CategoriesModelsCategory.fromJson(v));
      });
      category = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (category != null) {
      final v = category;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['category'] = arr0;
    }
    return data;
  }
}
