///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateBookinModelBookingDropLocation {
/*
{
  "type": "Point",
  "coordinates": [
    83.37816239552401
  ]
}
*/

  String? type;
  List<double?>? coordinates;

  CreateBookinModelBookingDropLocation({
    this.type,
    this.coordinates,
  });
  CreateBookinModelBookingDropLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class CreateBookinModelBookingPickupLocation {
/*
{
  "type": "Point",
  "coordinates": [
    83.37816239552401
  ],
  "address": "Gorakhpur"
}
*/

  String? type;
  List<double?>? coordinates;
  String? address;

  CreateBookinModelBookingPickupLocation({
    this.type,
    this.coordinates,
    this.address,
  });
  CreateBookinModelBookingPickupLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['address'] = address;
    return data;
  }
}

class CreateBookinModelBooking {
/*
{
  "user": "637b3573e25e4f6d1227a1de",
  "car": "637b37064bab010aa878e348",
  "status": "in-progress",
  "pickupTime": "",
  "pickupLocation": {
    "type": "Point",
    "coordinates": [
      83.37816239552401
    ],
    "address": "Gorakhpur"
  },
  "dropTime": "",
  "dropLocation": {
    "type": "Point",
    "coordinates": [
      83.37816239552401
    ]
  },
  "cancelReason": "",
  "isPaymentSuccess": false,
  "paymentMethod": "",
  "isDeleted": false,
  "_id": "63a2e79b33e4a03b10a8a279",
  "createdAt": "2022-12-21T11:01:47.874Z",
  "updatedAt": "2022-12-21T11:01:47.874Z"
}
*/

  String? user;
  String? car;
  String? status;
  String? pickupTime;
  CreateBookinModelBookingPickupLocation? pickupLocation;
  String? dropTime;
  CreateBookinModelBookingDropLocation? dropLocation;
  String? cancelReason;
  bool? isPaymentSuccess;
  String? paymentMethod;
  bool? isDeleted;
  String? Id;
  String? createdAt;
  String? updatedAt;

  CreateBookinModelBooking({
    this.user,
    this.car,
    this.status,
    this.pickupTime,
    this.pickupLocation,
    this.dropTime,
    this.dropLocation,
    this.cancelReason,
    this.isPaymentSuccess,
    this.paymentMethod,
    this.isDeleted,
    this.Id,
    this.createdAt,
    this.updatedAt,
  });
  CreateBookinModelBooking.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toString();
    car = json['car']?.toString();
    status = json['status']?.toString();
    pickupTime = json['pickupTime']?.toString();
    pickupLocation = (json['pickupLocation'] != null) ? CreateBookinModelBookingPickupLocation.fromJson(json['pickupLocation']) : null;
    dropTime = json['dropTime']?.toString();
    dropLocation = (json['dropLocation'] != null) ? CreateBookinModelBookingDropLocation.fromJson(json['dropLocation']) : null;
    cancelReason = json['cancelReason']?.toString();
    isPaymentSuccess = json['isPaymentSuccess'];
    paymentMethod = json['paymentMethod']?.toString();
    isDeleted = json['isDeleted'];
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['car'] = car;
    data['status'] = status;
    data['pickupTime'] = pickupTime;
    if (pickupLocation != null) {
      data['pickupLocation'] = pickupLocation!.toJson();
    }
    data['dropTime'] = dropTime;
    if (dropLocation != null) {
      data['dropLocation'] = dropLocation!.toJson();
    }
    data['cancelReason'] = cancelReason;
    data['isPaymentSuccess'] = isPaymentSuccess;
    data['paymentMethod'] = paymentMethod;
    data['isDeleted'] = isDeleted;
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class CreateBookinModel {
/*
{
  "status": true,
  "message": "Booking created.",
  "booking": {
    "user": "637b3573e25e4f6d1227a1de",
    "car": "637b37064bab010aa878e348",
    "status": "in-progress",
    "pickupTime": "",
    "pickupLocation": {
      "type": "Point",
      "coordinates": [
        83.37816239552401
      ],
      "address": "Gorakhpur"
    },
    "dropTime": "",
    "dropLocation": {
      "type": "Point",
      "coordinates": [
        83.37816239552401
      ]
    },
    "cancelReason": "",
    "isPaymentSuccess": false,
    "paymentMethod": "",
    "isDeleted": false,
    "_id": "63a2e79b33e4a03b10a8a279",
    "createdAt": "2022-12-21T11:01:47.874Z",
    "updatedAt": "2022-12-21T11:01:47.874Z"
  }
}
*/

  bool? status;
  String? message;
  CreateBookinModelBooking? booking;

  CreateBookinModel({
    this.status,
    this.message,
    this.booking,
  });
  CreateBookinModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    booking = (json['booking'] != null) ? CreateBookinModelBooking.fromJson(json['booking']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (booking != null) {
      data['booking'] = booking!.toJson();
    }
    return data;
  }
}
