///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EndRideDataDropLocation {
/*
{
  "type": "Point",
  "coordinates": [
    80.9229409563887
  ],
  "address": "Lucknow"
}
*/

  String? type;
  List<double?>? coordinates;
  String? address;

  EndRideDataDropLocation({
    this.type,
    this.coordinates,
    this.address,
  });
  EndRideDataDropLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['address'] = address;
    return data;
  }
}

class EndRideDataPickupLocation {
/*
{
  "type": "Point",
  "coordinates": [
    38.684811
  ],
  "address": "12801 Fair Oaks Blvd, ,California, 95610 "
}
*/

  String? type;
  List<double?>? coordinates;
  String? address;

  EndRideDataPickupLocation({
    this.type,
    this.coordinates,
    this.address,
  });
  EndRideDataPickupLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['address'] = address;
    return data;
  }
}

class EndRideData {
/*
{
  "pickupLocation": {
    "type": "Point",
    "coordinates": [
      38.684811
    ],
    "address": "12801 Fair Oaks Blvd, ,California, 95610 "
  },
  "dropLocation": {
    "type": "Point",
    "coordinates": [
      80.9229409563887
    ],
    "address": "Lucknow"
  },
  "_id": "646de27b611de76d1bc4a1be",
  "user": "6388c33fc6b2d524a07fdc15",
  "car": "63f377e5d6cc2f883de290ce",
  "qnr": "6DB9853D00FFF005",
  "status": "completed",
  "pickupTime": "2023-05-24T10:12:50.959Z",
  "dropTime": "2023-05-24T10:14:25.558Z",
  "cancelReason": "",
  "cancelledBy": "null",
  "isPaymentSuccess": false,
  "paymentMethod": "null",
  "rideEndedBy": "user",
  "waitingTime": 165,
  "additionalWaitingTime": 0,
  "path": [
    [
      "38.684776"
    ]
  ],
  "isDeleted": false,
  "createdAt": "2023-05-24T10:10:03.599Z",
  "updatedAt": "2023-05-24T10:14:27.696Z",
  "paymentStep": "initialPayment",
  "id": "646de27b611de76d1bc4a1be"
}
*/

  EndRideDataPickupLocation? pickupLocation;
  EndRideDataDropLocation? dropLocation;
  String? Id;
  String? user;
  String? car;
  String? qnr;
  String? status;
  String? pickupTime;
  String? dropTime;
  String? cancelReason;
  String? cancelledBy;
  bool? isPaymentSuccess;
  String? paymentMethod;
  String? rideEndedBy;
  int? waitingTime;
  int? additionalWaitingTime;
  List<List<String?>?>? path;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  String? paymentStep;
  String? id;

  EndRideData({
    this.pickupLocation,
    this.dropLocation,
    this.Id,
    this.user,
    this.car,
    this.qnr,
    this.status,
    this.pickupTime,
    this.dropTime,
    this.cancelReason,
    this.cancelledBy,
    this.isPaymentSuccess,
    this.paymentMethod,
    this.rideEndedBy,
    this.waitingTime,
    this.additionalWaitingTime,
    this.path,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.paymentStep,
    this.id,
  });
  EndRideData.fromJson(Map<String, dynamic> json) {
    pickupLocation = (json['pickupLocation'] != null) ? EndRideDataPickupLocation.fromJson(json['pickupLocation']) : null;
    dropLocation = (json['dropLocation'] != null) ? EndRideDataDropLocation.fromJson(json['dropLocation']) : null;
    Id = json['_id']?.toString();
    user = json['user']?.toString();
    car = json['car']?.toString();
    qnr = json['qnr']?.toString();
    status = json['status']?.toString();
    pickupTime = json['pickupTime']?.toString();
    dropTime = json['dropTime']?.toString();
    cancelReason = json['cancelReason']?.toString();
    cancelledBy = json['cancelledBy']?.toString();
    isPaymentSuccess = json['isPaymentSuccess'];
    paymentMethod = json['paymentMethod']?.toString();
    rideEndedBy = json['rideEndedBy']?.toString();
    waitingTime = json['waitingTime']?.toInt();
    additionalWaitingTime = json['additionalWaitingTime']?.toInt();
    if (json['path'] != null) {
      final v = json['path'];
      final arr0 = <List<String>>[];
      v.forEach((v) {
        final arr1 = <String>[];
        v.forEach((v) {
          arr1.add(v.toString());
        });
        arr0.add(arr1);
      });
      path = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    paymentStep = json['paymentStep']?.toString();
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pickupLocation != null) {
      data['pickupLocation'] = pickupLocation!.toJson();
    }
    if (dropLocation != null) {
      data['dropLocation'] = dropLocation!.toJson();
    }
    data['_id'] = Id;
    data['user'] = user;
    data['car'] = car;
    data['qnr'] = qnr;
    data['status'] = status;
    data['pickupTime'] = pickupTime;
    data['dropTime'] = dropTime;
    data['cancelReason'] = cancelReason;
    data['cancelledBy'] = cancelledBy;
    data['isPaymentSuccess'] = isPaymentSuccess;
    data['paymentMethod'] = paymentMethod;
    data['rideEndedBy'] = rideEndedBy;
    data['waitingTime'] = waitingTime;
    data['additionalWaitingTime'] = additionalWaitingTime;
    if (path != null) {
      final v = path;
      final arr0 = [];
      v!.forEach((v) {
        final arr1 = [];
        v!.forEach((v) {
          arr1.add(v);
        });
        arr0.add(arr1);
      });
      data['path'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['paymentStep'] = paymentStep;
    data['id'] = id;
    return data;
  }
}

class EndRide {
/*
{
  "status": true,
  "message": "Ride ended.",
  "data": {
    "pickupLocation": {
      "type": "Point",
      "coordinates": [
        38.684811
      ],
      "address": "12801 Fair Oaks Blvd, ,California, 95610 "
    },
    "dropLocation": {
      "type": "Point",
      "coordinates": [
        80.9229409563887
      ],
      "address": "Lucknow"
    },
    "_id": "646de27b611de76d1bc4a1be",
    "user": "6388c33fc6b2d524a07fdc15",
    "car": "63f377e5d6cc2f883de290ce",
    "qnr": "6DB9853D00FFF005",
    "status": "completed",
    "pickupTime": "2023-05-24T10:12:50.959Z",
    "dropTime": "2023-05-24T10:14:25.558Z",
    "cancelReason": "",
    "cancelledBy": "null",
    "isPaymentSuccess": false,
    "paymentMethod": "null",
    "rideEndedBy": "user",
    "waitingTime": 165,
    "additionalWaitingTime": 0,
    "path": [
      [
        "38.684776"
      ]
    ],
    "isDeleted": false,
    "createdAt": "2023-05-24T10:10:03.599Z",
    "updatedAt": "2023-05-24T10:14:27.696Z",
    "paymentStep": "initialPayment",
    "id": "646de27b611de76d1bc4a1be"
  }
}
*/

  bool? status;
  String? message;
  EndRideData? data;

  EndRide({
    this.status,
    this.message,
    this.data,
  });
  EndRide.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? EndRideData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
