///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCarsCarsPosition {
/*
{
  "type": "Point",
  "coordinates": [
    127.9
  ]
}
*/

  String? type;
  List<double?>? coordinates;

  GetCarsCarsPosition({
    this.type,
    this.coordinates,
  });
  GetCarsCarsPosition.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class GetCarsCars {
/*
{
  "position": {
    "type": "Point",
    "coordinates": [
      127.9
    ]
  },
  "_id": "63f4b3636c2c9559d406b907",
  "brand": "Cadillac",
  "model": "Model M",
  "qnr": "6DB9853D00FFF015",
  "seatCapacity": 2,
  "color": "black",
  "fuelType": "fuel",
  "category": "suv",
  "images": [
    "https://stimg.cardekho.com/images/carexteriorimages/930x620/Rolls-Royce/Ghost/8051/1601280317407/front-left-side-47.jpg"
  ],
  "isDamaged": false,
  "status": "active",
  "fuel_level": 0,
  "bookingStatus": "idle",
  "isDeleted": false,
  "createdAt": "2023-02-21T12:04:51.608Z",
  "updatedAt": "2023-02-21T12:04:51.608Z"
}
*/

  GetCarsCarsPosition? position;
  String? Id;
  String? brand;
  String? model;
  String? qnr;
  int? seatCapacity;
  String? color;
  String? fuelType;
  String? category;
  List<String?>? images;
  bool? isDamaged;
  String? status;
  int? fuelLevel;
  String? bookingStatus;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;

  GetCarsCars({
    this.position,
    this.Id,
    this.brand,
    this.model,
    this.qnr,
    this.seatCapacity,
    this.color,
    this.fuelType,
    this.category,
    this.images,
    this.isDamaged,
    this.status,
    this.fuelLevel,
    this.bookingStatus,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
  });
  GetCarsCars.fromJson(Map<String, dynamic> json) {
    position = (json['position'] != null) ? GetCarsCarsPosition.fromJson(json['position']) : null;
    Id = json['_id']?.toString();
    brand = json['brand']?.toString();
    model = json['model']?.toString();
    qnr = json['qnr']?.toString();
    seatCapacity = json['seatCapacity']?.toInt();
    color = json['color']?.toString();
    fuelType = json['fuelType']?.toString();
    category = json['category']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
    isDamaged = json['isDamaged'];
    status = json['status']?.toString();
    fuelLevel = json['fuel_level']?.toInt();
    bookingStatus = json['bookingStatus']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (position != null) {
      data['position'] = position!.toJson();
    }
    data['_id'] = Id;
    data['brand'] = brand;
    data['model'] = model;
    data['qnr'] = qnr;
    data['seatCapacity'] = seatCapacity;
    data['color'] = color;
    data['fuelType'] = fuelType;
    data['category'] = category;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['images'] = arr0;
    }
    data['isDamaged'] = isDamaged;
    data['status'] = status;
    data['fuel_level'] = fuelLevel;
    data['bookingStatus'] = bookingStatus;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class GetCars {
/*
{
  "status": true,
  "message": "Get all cars",
  "cars": [
    {
      "position": {
        "type": "Point",
        "coordinates": [
          127.9
        ]
      },
      "_id": "63f4b3636c2c9559d406b907",
      "brand": "Cadillac",
      "model": "Model M",
      "qnr": "6DB9853D00FFF015",
      "seatCapacity": 2,
      "color": "black",
      "fuelType": "fuel",
      "category": "suv",
      "images": [
        "https://stimg.cardekho.com/images/carexteriorimages/930x620/Rolls-Royce/Ghost/8051/1601280317407/front-left-side-47.jpg"
      ],
      "isDamaged": false,
      "status": "active",
      "fuel_level": 0,
      "bookingStatus": "idle",
      "isDeleted": false,
      "createdAt": "2023-02-21T12:04:51.608Z",
      "updatedAt": "2023-02-21T12:04:51.608Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<GetCarsCars?>? cars;

  GetCars({
    this.status,
    this.message,
    this.cars,
  });
  GetCars.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['cars'] != null) {
      final v = json['cars'];
      final arr0 = <GetCarsCars>[];
      v.forEach((v) {
        arr0.add(GetCarsCars.fromJson(v));
      });
      cars = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (cars != null) {
      final v = cars;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cars'] = arr0;
    }
    return data;
  }
}
