///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetCarsCars {
/*
{
  "_id": "637b37064bab010aa878e348",
  "brand": "Tesla",
  "model": "Model Y",
  "seatCapacity": 4,
  "color": "black",
  "carType": "electrical",
  "category": "suv",
  "createdAt": "2022-11-21T08:29:58.881Z",
  "updatedAt": "2022-11-21T08:29:58.881Z"
}
*/

  String? Id;
  String? brand;
  String? model;
  int? seatCapacity;
  String? color;
  String? carType;
  String? category;
  String? createdAt;
  String? updatedAt;

  GetCarsCars({
    this.Id,
    this.brand,
    this.model,
    this.seatCapacity,
    this.color,
    this.carType,
    this.category,
    this.createdAt,
    this.updatedAt,
  });
  GetCarsCars.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    brand = json['brand']?.toString();
    model = json['model']?.toString();
    seatCapacity = json['seatCapacity']?.toInt();
    color = json['color']?.toString();
    carType = json['carType']?.toString();
    category = json['category']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['brand'] = brand;
    data['model'] = model;
    data['seatCapacity'] = seatCapacity;
    data['color'] = color;
    data['carType'] = carType;
    data['category'] = category;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class GetCars {
/*
{
  "status": true,
  "message": "Get all cars",
  "cars": [
    {
      "_id": "637b37064bab010aa878e348",
      "brand": "Tesla",
      "model": "Model Y",
      "seatCapacity": 4,
      "color": "black",
      "carType": "electrical",
      "category": "suv",
      "createdAt": "2022-11-21T08:29:58.881Z",
      "updatedAt": "2022-11-21T08:29:58.881Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<GetCarsCars?>? cars;

  GetCars({
    this.status,
    this.message,
    this.cars,
  });
  GetCars.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['cars'] != null) {
      final v = json['cars'];
      final arr0 = <GetCarsCars>[];
      v.forEach((v) {
        arr0.add(GetCarsCars.fromJson(v));
      });
      cars = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (cars != null) {
      final v = cars;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cars'] = arr0;
    }
    return data;
  }
}
