///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BookingDetailsModelsDataInspectionsCarImagesAfterRide {
/*
{
  "respectiveSide": "Front Hood",
  "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
  "_id": "6530cdc34beb27c50e37cb35"
}
*/

  String? respectiveSide;
  String? image;
  String? Id;

  BookingDetailsModelsDataInspectionsCarImagesAfterRide({
    this.respectiveSide,
    this.image,
    this.Id,
  });
  BookingDetailsModelsDataInspectionsCarImagesAfterRide.fromJson(Map<String, dynamic> json) {
    respectiveSide = json['respectiveSide']?.toString();
    image = json['image']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['respectiveSide'] = respectiveSide;
    data['image'] = image;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailsModelsDataInspectionsCarImagesBeforeRide {
/*
{
  "respectiveSide": "Front Hood",
  "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
  "_id": "6530cdc34beb27c50e37cb35"
}
*/

  String? respectiveSide;
  String? image;
  String? Id;

  BookingDetailsModelsDataInspectionsCarImagesBeforeRide({
    this.respectiveSide,
    this.image,
    this.Id,
  });
  BookingDetailsModelsDataInspectionsCarImagesBeforeRide.fromJson(Map<String, dynamic> json) {
    respectiveSide = json['respectiveSide']?.toString();
    image = json['image']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['respectiveSide'] = respectiveSide;
    data['image'] = image;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailsModelsDataInspections {
/*
{
  "_id": "6530cdc34beb27c50e37cb34",
  "booking": "6530cc6f4beb27c50e37cb01",
  "carImagesBeforeRide": [
    {
      "respectiveSide": "Front Hood",
      "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
      "_id": "6530cdc34beb27c50e37cb35"
    }
  ],
  "carImagesAfterRide": [
    {
      "respectiveSide": "Front Hood",
      "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
      "_id": "6530cdc34beb27c50e37cb35"
    }
  ],
  "createdAt": "2023-10-19T06:33:39.048Z",
  "updatedAt": "2023-10-19T06:33:39.048Z"
}
*/

  String? Id;
  String? booking;
  List<BookingDetailsModelsDataInspectionsCarImagesBeforeRide?>? carImagesBeforeRide;
  List<BookingDetailsModelsDataInspectionsCarImagesAfterRide?>? carImagesAfterRide;
  String? createdAt;
  String? updatedAt;

  BookingDetailsModelsDataInspections({
    this.Id,
    this.booking,
    this.carImagesBeforeRide,
    this.carImagesAfterRide,
    this.createdAt,
    this.updatedAt,
  });
  BookingDetailsModelsDataInspections.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    booking = json['booking']?.toString();
    if (json['carImagesBeforeRide'] != null) {
      final v = json['carImagesBeforeRide'];
      final arr0 = <BookingDetailsModelsDataInspectionsCarImagesBeforeRide>[];
      v.forEach((v) {
        arr0.add(BookingDetailsModelsDataInspectionsCarImagesBeforeRide.fromJson(v));
      });
      carImagesBeforeRide = arr0;
    }
    if (json['carImagesAfterRide'] != null) {
      final v = json['carImagesAfterRide'];
      final arr0 = <BookingDetailsModelsDataInspectionsCarImagesAfterRide>[];
      v.forEach((v) {
        arr0.add(BookingDetailsModelsDataInspectionsCarImagesAfterRide.fromJson(v));
      });
      carImagesAfterRide = arr0;
    }
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['booking'] = booking;
    if (carImagesBeforeRide != null) {
      final v = carImagesBeforeRide;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['carImagesBeforeRide'] = arr0;
    }
    if (carImagesAfterRide != null) {
      final v = carImagesAfterRide;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['carImagesAfterRide'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class BookingDetailsModelsDataIgnitionEvents {
/*
{
  "status": "on",
  "time": "2023-10-19T06:45:22.000Z",
  "_id": "6530d0854beb27c50e37cbe3"
}
*/

  String? status;
  String? time;
  String? Id;

  BookingDetailsModelsDataIgnitionEvents({
    this.status,
    this.time,
    this.Id,
  });
  BookingDetailsModelsDataIgnitionEvents.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    time = json['time']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['time'] = time;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailsModelsDataTripDataEventStatusPosition {
/*
{
  "timestamp": "2023-10-19T06:32:22.000Z",
  "lon": -121.381905,
  "lat": 38.617905,
  "hdop": 0.65,
  "speed_over_ground": 0,
  "quality": 1,
  "satellites_in_use": 18,
  "altitude": 20,
  "heading": 161,
  "navigation_solution": "standalone_3d"
}
*/

  String? timestamp;
  double? lon;
  double? lat;
  double? hdop;
  int? speedOverGround;
  int? quality;
  int? satellitesInUse;
  int? altitude;
  int? heading;
  String? navigationSolution;

  BookingDetailsModelsDataTripDataEventStatusPosition({
    this.timestamp,
    this.lon,
    this.lat,
    this.hdop,
    this.speedOverGround,
    this.quality,
    this.satellitesInUse,
    this.altitude,
    this.heading,
    this.navigationSolution,
  });
  BookingDetailsModelsDataTripDataEventStatusPosition.fromJson(Map<String, dynamic> json) {
    timestamp = json['timestamp']?.toString();
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
    hdop = json['hdop']?.toDouble();
    speedOverGround = json['speed_over_ground']?.toInt();
    quality = json['quality']?.toInt();
    satellitesInUse = json['satellites_in_use']?.toInt();
    altitude = json['altitude']?.toInt();
    heading = json['heading']?.toInt();
    navigationSolution = json['navigation_solution']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['timestamp'] = timestamp;
    data['lon'] = lon;
    data['lat'] = lat;
    data['hdop'] = hdop;
    data['speed_over_ground'] = speedOverGround;
    data['quality'] = quality;
    data['satellites_in_use'] = satellitesInUse;
    data['altitude'] = altitude;
    data['heading'] = heading;
    data['navigation_solution'] = navigationSolution;
    return data;
  }
}

class BookingDetailsModelsDataTripDataEventStatusAlarmInputs {
/*
{
  "1": "OFF",
  "2": "OFF"
}
*/

  String? the1;
  String? the2;

  BookingDetailsModelsDataTripDataEventStatusAlarmInputs({
    this.the1,
    this.the2,
  });
  BookingDetailsModelsDataTripDataEventStatusAlarmInputs.fromJson(Map<String, dynamic> json) {
    the1 = json['1']?.toString();
    the2 = json['2']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['1'] = the1;
    data['2'] = the2;
    return data;
  }
}

class BookingDetailsModelsDataTripDataEventStatus {
/*
{
  "fuel_level": 21,
  "mileage": 28457,
  "mileage_since_immobilizer_unlock": 1,
  "immobilizer": "unlocked",
  "ignition": "off",
  "central_lock": "locked",
  "keyfob": "in",
  "speed": 0,
  "bluetooth_connection": "disconnected",
  "board_voltage": 12.73,
  "seconds_since_immobilizer_unlock": 0,
  "central_lock_last_command": "locked",
  "alarm_input": "off",
  "alarm_input_2": "off",
  "alarm_inputs": {
    "1": "OFF",
    "2": "OFF"
  },
  "low_fuel_level_alarm": true,
  "low_battery_level_alarm": false,
  "relay_value": 0,
  "tilt_status": "unknown",
  "position": {
    "timestamp": "2023-10-19T06:32:22.000Z",
    "lon": -121.381905,
    "lat": 38.617905,
    "hdop": 0.65,
    "speed_over_ground": 0,
    "quality": 1,
    "satellites_in_use": 18,
    "altitude": 20,
    "heading": 161,
    "navigation_solution": "standalone_3d"
  },
  "bluetooth_authenticated": false
}
*/

  int? fuelLevel;
  int? mileage;
  int? mileageSinceImmobilizerUnlock;
  String? immobilizer;
  String? ignition;
  String? centralLock;
  String? keyfob;
  int? speed;
  String? bluetoothConnection;
  double? boardVoltage;
  int? secondsSinceImmobilizerUnlock;
  String? centralLockLastCommand;
  String? alarmInput;
  String? alarmInput_2;
  BookingDetailsModelsDataTripDataEventStatusAlarmInputs? alarmInputs;
  bool? lowFuelLevelAlarm;
  bool? lowBatteryLevelAlarm;
  int? relayValue;
  String? tiltStatus;
  BookingDetailsModelsDataTripDataEventStatusPosition? position;
  bool? bluetoothAuthenticated;

  BookingDetailsModelsDataTripDataEventStatus({
    this.fuelLevel,
    this.mileage,
    this.mileageSinceImmobilizerUnlock,
    this.immobilizer,
    this.ignition,
    this.centralLock,
    this.keyfob,
    this.speed,
    this.bluetoothConnection,
    this.boardVoltage,
    this.secondsSinceImmobilizerUnlock,
    this.centralLockLastCommand,
    this.alarmInput,
    this.alarmInput_2,
    this.alarmInputs,
    this.lowFuelLevelAlarm,
    this.lowBatteryLevelAlarm,
    this.relayValue,
    this.tiltStatus,
    this.position,
    this.bluetoothAuthenticated,
  });
  BookingDetailsModelsDataTripDataEventStatus.fromJson(Map<String, dynamic> json) {
    fuelLevel = json['fuel_level']?.toInt();
    mileage = json['mileage']?.toInt();
    mileageSinceImmobilizerUnlock = json['mileage_since_immobilizer_unlock']?.toInt();
    immobilizer = json['immobilizer']?.toString();
    ignition = json['ignition']?.toString();
    centralLock = json['central_lock']?.toString();
    keyfob = json['keyfob']?.toString();
    speed = json['speed']?.toInt();
    bluetoothConnection = json['bluetooth_connection']?.toString();
    boardVoltage = json['board_voltage']?.toDouble();
    secondsSinceImmobilizerUnlock = json['seconds_since_immobilizer_unlock']?.toInt();
    centralLockLastCommand = json['central_lock_last_command']?.toString();
    alarmInput = json['alarm_input']?.toString();
    alarmInput_2 = json['alarm_input_2']?.toString();
    alarmInputs = (json['alarm_inputs'] != null) ? BookingDetailsModelsDataTripDataEventStatusAlarmInputs.fromJson(json['alarm_inputs']) : null;
    lowFuelLevelAlarm = json['low_fuel_level_alarm'];
    lowBatteryLevelAlarm = json['low_battery_level_alarm'];
    relayValue = json['relay_value']?.toInt();
    tiltStatus = json['tilt_status']?.toString();
    position = (json['position'] != null) ? BookingDetailsModelsDataTripDataEventStatusPosition.fromJson(json['position']) : null;
    bluetoothAuthenticated = json['bluetooth_authenticated'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['fuel_level'] = fuelLevel;
    data['mileage'] = mileage;
    data['mileage_since_immobilizer_unlock'] = mileageSinceImmobilizerUnlock;
    data['immobilizer'] = immobilizer;
    data['ignition'] = ignition;
    data['central_lock'] = centralLock;
    data['keyfob'] = keyfob;
    data['speed'] = speed;
    data['bluetooth_connection'] = bluetoothConnection;
    data['board_voltage'] = boardVoltage;
    data['seconds_since_immobilizer_unlock'] = secondsSinceImmobilizerUnlock;
    data['central_lock_last_command'] = centralLockLastCommand;
    data['alarm_input'] = alarmInput;
    data['alarm_input_2'] = alarmInput_2;
    if (alarmInputs != null) {
      data['alarm_inputs'] = alarmInputs!.toJson();
    }
    data['low_fuel_level_alarm'] = lowFuelLevelAlarm;
    data['low_battery_level_alarm'] = lowBatteryLevelAlarm;
    data['relay_value'] = relayValue;
    data['tilt_status'] = tiltStatus;
    if (position != null) {
      data['position'] = position!.toJson();
    }
    data['bluetooth_authenticated'] = bluetoothAuthenticated;
    return data;
  }
}

class BookingDetailsModelsDataTripDataEvent {
/*
{
  "timestamp": "2023-10-19T06:33:42.000Z",
  "reasons": [
    "immobilizer_changed"
  ],
  "source": "server",
  "request_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
  "flow_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
  "status": {
    "fuel_level": 21,
    "mileage": 28457,
    "mileage_since_immobilizer_unlock": 1,
    "immobilizer": "unlocked",
    "ignition": "off",
    "central_lock": "locked",
    "keyfob": "in",
    "speed": 0,
    "bluetooth_connection": "disconnected",
    "board_voltage": 12.73,
    "seconds_since_immobilizer_unlock": 0,
    "central_lock_last_command": "locked",
    "alarm_input": "off",
    "alarm_input_2": "off",
    "alarm_inputs": {
      "1": "OFF",
      "2": "OFF"
    },
    "low_fuel_level_alarm": true,
    "low_battery_level_alarm": false,
    "relay_value": 0,
    "tilt_status": "unknown",
    "position": {
      "timestamp": "2023-10-19T06:32:22.000Z",
      "lon": -121.381905,
      "lat": 38.617905,
      "hdop": 0.65,
      "speed_over_ground": 0,
      "quality": 1,
      "satellites_in_use": 18,
      "altitude": 20,
      "heading": 161,
      "navigation_solution": "standalone_3d"
    },
    "bluetooth_authenticated": false
  }
}
*/

  String? timestamp;
  List<String?>? reasons;
  String? source;
  String? requestId;
  String? flowId;
  BookingDetailsModelsDataTripDataEventStatus? status;

  BookingDetailsModelsDataTripDataEvent({
    this.timestamp,
    this.reasons,
    this.source,
    this.requestId,
    this.flowId,
    this.status,
  });
  BookingDetailsModelsDataTripDataEvent.fromJson(Map<String, dynamic> json) {
    timestamp = json['timestamp']?.toString();
    if (json['reasons'] != null) {
      final v = json['reasons'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      reasons = arr0;
    }
    source = json['source']?.toString();
    requestId = json['request_id']?.toString();
    flowId = json['flow_id']?.toString();
    status = (json['status'] != null) ? BookingDetailsModelsDataTripDataEventStatus.fromJson(json['status']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['timestamp'] = timestamp;
    if (reasons != null) {
      final v = reasons;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['reasons'] = arr0;
    }
    data['source'] = source;
    data['request_id'] = requestId;
    data['flow_id'] = flowId;
    if (status != null) {
      data['status'] = status!.toJson();
    }
    return data;
  }
}

class BookingDetailsModelsDataTripData {
/*
{
  "qnr": "6DB9853D00FFF005",
  "reception_timestamp": "2023-10-19T06:33:44.510Z",
  "event": {
    "timestamp": "2023-10-19T06:33:42.000Z",
    "reasons": [
      "immobilizer_changed"
    ],
    "source": "server",
    "request_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
    "flow_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
    "status": {
      "fuel_level": 21,
      "mileage": 28457,
      "mileage_since_immobilizer_unlock": 1,
      "immobilizer": "unlocked",
      "ignition": "off",
      "central_lock": "locked",
      "keyfob": "in",
      "speed": 0,
      "bluetooth_connection": "disconnected",
      "board_voltage": 12.73,
      "seconds_since_immobilizer_unlock": 0,
      "central_lock_last_command": "locked",
      "alarm_input": "off",
      "alarm_input_2": "off",
      "alarm_inputs": {
        "1": "OFF",
        "2": "OFF"
      },
      "low_fuel_level_alarm": true,
      "low_battery_level_alarm": false,
      "relay_value": 0,
      "tilt_status": "unknown",
      "position": {
        "timestamp": "2023-10-19T06:32:22.000Z",
        "lon": -121.381905,
        "lat": 38.617905,
        "hdop": 0.65,
        "speed_over_ground": 0,
        "quality": 1,
        "satellites_in_use": 18,
        "altitude": 20,
        "heading": 161,
        "navigation_solution": "standalone_3d"
      },
      "bluetooth_authenticated": false
    }
  }
}
*/

  String? qnr;
  String? receptionTimestamp;
  BookingDetailsModelsDataTripDataEvent? event;

  BookingDetailsModelsDataTripData({
    this.qnr,
    this.receptionTimestamp,
    this.event,
  });
  BookingDetailsModelsDataTripData.fromJson(Map<String, dynamic> json) {
    qnr = json['qnr']?.toString();
    receptionTimestamp = json['reception_timestamp']?.toString();
    event = (json['event'] != null) ? BookingDetailsModelsDataTripDataEvent.fromJson(json['event']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['qnr'] = qnr;
    data['reception_timestamp'] = receptionTimestamp;
    if (event != null) {
      data['event'] = event!.toJson();
    }
    return data;
  }
}

class BookingDetailsModelsDataCarPosition {
/*
{
  "type": "Point",
  "coordinates": [
    -121.382538
  ]
}
*/

  String? type;
  List<double?>? coordinates;

  BookingDetailsModelsDataCarPosition({
    this.type,
    this.coordinates,
  });
  BookingDetailsModelsDataCarPosition.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class BookingDetailsModelsDataCar {
/*
{
  "position": {
    "type": "Point",
    "coordinates": [
      -121.382538
    ]
  },
  "_id": "63f377e5d6cc2f883de290ce",
  "brand": "Toyota",
  "model": "Prius",
  "qnr": "6DB9853D00FFF005",
  "seatCapacity": 5,
  "color": "White",
  "carType": "fuel",
  "images": [
    "https://zammadl.s3.us-west-1.amazonaws.com/zammadl-2021_toyota_prius_prime_angularfront.jpg"
  ],
  "isDamaged": false,
  "status": "active",
  "bookingStatus": "booked",
  "isDeleted": false,
  "createdAt": "2023-02-20T13:38:45.912Z",
  "updatedAt": "2023-10-19T06:47:33.379Z",
  "category": "sedan",
  "fuelType": "fuel",
  "bluetooth_connection": "disconnected",
  "board_voltage": 12.49,
  "ignition": "on",
  "immobilizer": "unlocked",
  "mileage": 28457,
  "mileage_since_immobilizer_unlock": 0,
  "alarm_input": "off",
  "alarm_input_2": "off",
  "low_battery_level_alarm": false,
  "low_fuel_level_alarm": true,
  "relay_value": 0,
  "qrCodeImage": "https://www.hellotech.com/guide/wp-content/uploads/2020/05/HelloTech-qr-code.jpg",
  "central_lock": "locked",
  "central_lock_last_command": "locked",
  "keyfob": "in",
  "vehicle_identification_number": "",
  "vehicle_license_plate": "",
  "isPaused": false,
  "speed": 0,
  "fuel_level": 21
}
*/

  BookingDetailsModelsDataCarPosition? position;
  String? Id;
  String? brand;
  String? model;
  String? qnr;
  int? seatCapacity;
  String? color;
  String? carType;
  List<String?>? images;
  bool? isDamaged;
  String? status;
  String? bookingStatus;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  String? category;
  String? fuelType;
  String? bluetoothConnection;
  double? boardVoltage;
  String? ignition;
  String? immobilizer;
  int? mileage;
  int? mileageSinceImmobilizerUnlock;
  String? alarmInput;
  String? alarmInput_2;
  bool? lowBatteryLevelAlarm;
  bool? lowFuelLevelAlarm;
  int? relayValue;
  String? qrCodeImage;
  String? centralLock;
  String? centralLockLastCommand;
  String? keyfob;
  String? vehicleIdentificationNumber;
  String? vehicleLicensePlate;
  bool? isPaused;
  int? speed;
  int? fuelLevel;

  BookingDetailsModelsDataCar({
    this.position,
    this.Id,
    this.brand,
    this.model,
    this.qnr,
    this.seatCapacity,
    this.color,
    this.carType,
    this.images,
    this.isDamaged,
    this.status,
    this.bookingStatus,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.category,
    this.fuelType,
    this.bluetoothConnection,
    this.boardVoltage,
    this.ignition,
    this.immobilizer,
    this.mileage,
    this.mileageSinceImmobilizerUnlock,
    this.alarmInput,
    this.alarmInput_2,
    this.lowBatteryLevelAlarm,
    this.lowFuelLevelAlarm,
    this.relayValue,
    this.qrCodeImage,
    this.centralLock,
    this.centralLockLastCommand,
    this.keyfob,
    this.vehicleIdentificationNumber,
    this.vehicleLicensePlate,
    this.isPaused,
    this.speed,
    this.fuelLevel,
  });
  BookingDetailsModelsDataCar.fromJson(Map<String, dynamic> json) {
    position = (json['position'] != null) ? BookingDetailsModelsDataCarPosition.fromJson(json['position']) : null;
    Id = json['_id']?.toString();
    brand = json['brand']?.toString();
    model = json['model']?.toString();
    qnr = json['qnr']?.toString();
    seatCapacity = json['seatCapacity']?.toInt();
    color = json['color']?.toString();
    carType = json['carType']?.toString();
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
    isDamaged = json['isDamaged'];
    status = json['status']?.toString();
    bookingStatus = json['bookingStatus']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    category = json['category']?.toString();
    fuelType = json['fuelType']?.toString();
    bluetoothConnection = json['bluetooth_connection']?.toString();
    boardVoltage = json['board_voltage']?.toDouble();
    ignition = json['ignition']?.toString();
    immobilizer = json['immobilizer']?.toString();
    mileage = json['mileage']?.toInt();
    mileageSinceImmobilizerUnlock = json['mileage_since_immobilizer_unlock']?.toInt();
    alarmInput = json['alarm_input']?.toString();
    alarmInput_2 = json['alarm_input_2']?.toString();
    lowBatteryLevelAlarm = json['low_battery_level_alarm'];
    lowFuelLevelAlarm = json['low_fuel_level_alarm'];
    relayValue = json['relay_value']?.toInt();
    qrCodeImage = json['qrCodeImage']?.toString();
    centralLock = json['central_lock']?.toString();
    centralLockLastCommand = json['central_lock_last_command']?.toString();
    keyfob = json['keyfob']?.toString();
    vehicleIdentificationNumber = json['vehicle_identification_number']?.toString();
    vehicleLicensePlate = json['vehicle_license_plate']?.toString();
    isPaused = json['isPaused'];
    speed = json['speed']?.toInt();
    fuelLevel = json['fuel_level']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (position != null) {
      data['position'] = position!.toJson();
    }
    data['_id'] = Id;
    data['brand'] = brand;
    data['model'] = model;
    data['qnr'] = qnr;
    data['seatCapacity'] = seatCapacity;
    data['color'] = color;
    data['carType'] = carType;
    if (images != null) {
      final v = images;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['images'] = arr0;
    }
    data['isDamaged'] = isDamaged;
    data['status'] = status;
    data['bookingStatus'] = bookingStatus;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['category'] = category;
    data['fuelType'] = fuelType;
    data['bluetooth_connection'] = bluetoothConnection;
    data['board_voltage'] = boardVoltage;
    data['ignition'] = ignition;
    data['immobilizer'] = immobilizer;
    data['mileage'] = mileage;
    data['mileage_since_immobilizer_unlock'] = mileageSinceImmobilizerUnlock;
    data['alarm_input'] = alarmInput;
    data['alarm_input_2'] = alarmInput_2;
    data['low_battery_level_alarm'] = lowBatteryLevelAlarm;
    data['low_fuel_level_alarm'] = lowFuelLevelAlarm;
    data['relay_value'] = relayValue;
    data['qrCodeImage'] = qrCodeImage;
    data['central_lock'] = centralLock;
    data['central_lock_last_command'] = centralLockLastCommand;
    data['keyfob'] = keyfob;
    data['vehicle_identification_number'] = vehicleIdentificationNumber;
    data['vehicle_license_plate'] = vehicleLicensePlate;
    data['isPaused'] = isPaused;
    data['speed'] = speed;
    data['fuel_level'] = fuelLevel;
    return data;
  }
}

class BookingDetailsModelsDataUserStripeCards {
/*
{
  "encryptedCode": "U2FsdGVkX1+W4TCBMcZNJC0Tk6R+kdN/x186dIePUxiu1KDtQCijARM8FPU6T+Bm4QEN/Wtc7l8hXs22busRnkvpQ1Xoc7wuRDwB0qhI+U1lCndFFnKMjLNbPNksLtP+q0Qv1jNIQFFt/UR9FBMlN7v7Tb4F9HRgUTfCjATvIEk=",
  "stripeCardId": "card_1N5lqvERG4ZXrlcJ1xsAzT9V",
  "_id": "645a035a49fea5271de9d913"
}
*/

  String? encryptedCode;
  String? stripeCardId;
  String? Id;

  BookingDetailsModelsDataUserStripeCards({
    this.encryptedCode,
    this.stripeCardId,
    this.Id,
  });
  BookingDetailsModelsDataUserStripeCards.fromJson(Map<String, dynamic> json) {
    encryptedCode = json['encryptedCode']?.toString();
    stripeCardId = json['stripeCardId']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['encryptedCode'] = encryptedCode;
    data['stripeCardId'] = stripeCardId;
    data['_id'] = Id;
    return data;
  }
}

class BookingDetailsModelsDataUserInsurance {
/*
{
  "insuranceNumber": "1234512345",
  "validTill": "09-09-1234",
  "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
}
*/

  String? insuranceNumber;
  String? validTill;
  String? image;

  BookingDetailsModelsDataUserInsurance({
    this.insuranceNumber,
    this.validTill,
    this.image,
  });
  BookingDetailsModelsDataUserInsurance.fromJson(Map<String, dynamic> json) {
    insuranceNumber = json['insuranceNumber']?.toString();
    validTill = json['validTill']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['insuranceNumber'] = insuranceNumber;
    data['validTill'] = validTill;
    data['image'] = image;
    return data;
  }
}

class BookingDetailsModelsDataUserDl {
/*
{
  "licenceNumber": "1234567890",
  "validTill": "02-09-1995",
  "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
}
*/

  String? licenceNumber;
  String? validTill;
  String? image;

  BookingDetailsModelsDataUserDl({
    this.licenceNumber,
    this.validTill,
    this.image,
  });
  BookingDetailsModelsDataUserDl.fromJson(Map<String, dynamic> json) {
    licenceNumber = json['licenceNumber']?.toString();
    validTill = json['validTill']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['licenceNumber'] = licenceNumber;
    data['validTill'] = validTill;
    data['image'] = image;
    return data;
  }
}

class BookingDetailsModelsDataUser {
/*
{
  "dl": {
    "licenceNumber": "1234567890",
    "validTill": "02-09-1995",
    "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
  },
  "insurance": {
    "insuranceNumber": "1234512345",
    "validTill": "09-09-1234",
    "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
  },
  "_id": "6388c33fc6b2d524a07fdc15",
  "name": "Aidabeg",
  "phone": "+919999999999",
  "email": "aidabeg.khidirov@gmail.com",
  "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-image_picker649446327842398215.jpg",
  "role": "user",
  "firebaseUid": "UcN7eGb1oVShfCwm3Ogwry6q9T93",
  "firebaseSignInProvider": "phone",
  "gender": "male",
  "address": "Janakpuri Delhi",
  "suspensionReason": "user suspend",
  "isSuspended": false,
  "noOfRides": 26,
  "isDeleted": false,
  "createdAt": "2022-12-01T15:07:43.680Z",
  "updatedAt": "2023-10-19T06:28:00.336Z",
  "dob": "1995-05-26T00:00:00.000Z",
  "isApproved": true,
  "totalTravelKm": 0,
  "stripeCustomerId": "cus_NrUqU0rlJ0QffW",
  "stripeCardId": "card_1Nznd1ERG4ZXrlcJjitNdhT9",
  "stripeCards": [
    {
      "encryptedCode": "U2FsdGVkX1+W4TCBMcZNJC0Tk6R+kdN/x186dIePUxiu1KDtQCijARM8FPU6T+Bm4QEN/Wtc7l8hXs22busRnkvpQ1Xoc7wuRDwB0qhI+U1lCndFFnKMjLNbPNksLtP+q0Qv1jNIQFFt/UR9FBMlN7v7Tb4F9HRgUTfCjATvIEk=",
      "stripeCardId": "card_1N5lqvERG4ZXrlcJ1xsAzT9V",
      "_id": "645a035a49fea5271de9d913"
    }
  ],
  "isRejected": false
}
*/

  BookingDetailsModelsDataUserDl? dl;
  BookingDetailsModelsDataUserInsurance? insurance;
  String? Id;
  String? name;
  String? phone;
  String? email;
  String? image;
  String? role;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? gender;
  String? address;
  String? suspensionReason;
  bool? isSuspended;
  int? noOfRides;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  String? dob;
  bool? isApproved;
  int? totalTravelKm;
  String? stripeCustomerId;
  String? stripeCardId;
  List<BookingDetailsModelsDataUserStripeCards?>? stripeCards;
  bool? isRejected;

  BookingDetailsModelsDataUser({
    this.dl,
    this.insurance,
    this.Id,
    this.name,
    this.phone,
    this.email,
    this.image,
    this.role,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.gender,
    this.address,
    this.suspensionReason,
    this.isSuspended,
    this.noOfRides,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.dob,
    this.isApproved,
    this.totalTravelKm,
    this.stripeCustomerId,
    this.stripeCardId,
    this.stripeCards,
    this.isRejected,
  });
  BookingDetailsModelsDataUser.fromJson(Map<String, dynamic> json) {
    dl = (json['dl'] != null) ? BookingDetailsModelsDataUserDl.fromJson(json['dl']) : null;
    insurance = (json['insurance'] != null) ? BookingDetailsModelsDataUserInsurance.fromJson(json['insurance']) : null;
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    role = json['role']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    gender = json['gender']?.toString();
    address = json['address']?.toString();
    suspensionReason = json['suspensionReason']?.toString();
    isSuspended = json['isSuspended'];
    noOfRides = json['noOfRides']?.toInt();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    dob = json['dob']?.toString();
    isApproved = json['isApproved'];
    totalTravelKm = json['totalTravelKm']?.toInt();
    stripeCustomerId = json['stripeCustomerId']?.toString();
    stripeCardId = json['stripeCardId']?.toString();
    if (json['stripeCards'] != null) {
      final v = json['stripeCards'];
      final arr0 = <BookingDetailsModelsDataUserStripeCards>[];
      v.forEach((v) {
        arr0.add(BookingDetailsModelsDataUserStripeCards.fromJson(v));
      });
      stripeCards = arr0;
    }
    isRejected = json['isRejected'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dl != null) {
      data['dl'] = dl!.toJson();
    }
    if (insurance != null) {
      data['insurance'] = insurance!.toJson();
    }
    data['_id'] = Id;
    data['name'] = name;
    data['phone'] = phone;
    data['email'] = email;
    data['image'] = image;
    data['role'] = role;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['gender'] = gender;
    data['address'] = address;
    data['suspensionReason'] = suspensionReason;
    data['isSuspended'] = isSuspended;
    data['noOfRides'] = noOfRides;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['dob'] = dob;
    data['isApproved'] = isApproved;
    data['totalTravelKm'] = totalTravelKm;
    data['stripeCustomerId'] = stripeCustomerId;
    data['stripeCardId'] = stripeCardId;
    if (stripeCards != null) {
      final v = stripeCards;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['stripeCards'] = arr0;
    }
    data['isRejected'] = isRejected;
    return data;
  }
}

class BookingDetailsModelsDataDropLocation {
/*
{
  "type": "Point",
  "coordinates": [
    -121.382538
  ],
  "address": ""
}
*/

  String? type;
  List<double?>? coordinates;
  String? address;

  BookingDetailsModelsDataDropLocation({
    this.type,
    this.coordinates,
    this.address,
  });
  BookingDetailsModelsDataDropLocation.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
    address = json['address']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    data['address'] = address;
    return data;
  }
}

class BookingDetailsModelsDataPickupLocation {
/*
{
  "address": "",
  "type": "Point",
  "coordinates": [
    -121.381905
  ]
}
*/

  String? address;
  String? type;
  List<double?>? coordinates;

  BookingDetailsModelsDataPickupLocation({
    this.address,
    this.type,
    this.coordinates,
  });
  BookingDetailsModelsDataPickupLocation.fromJson(Map<String, dynamic> json) {
    address = json['address']?.toString();
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['address'] = address;
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class BookingDetailsModelsData {
/*
{
  "pickupLocation": {
    "address": "",
    "type": "Point",
    "coordinates": [
      -121.381905
    ]
  },
  "dropLocation": {
    "type": "Point",
    "coordinates": [
      -121.382538
    ],
    "address": ""
  },
  "_id": "6530cc6f4beb27c50e37cb01",
  "user": {
    "dl": {
      "licenceNumber": "1234567890",
      "validTill": "02-09-1995",
      "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
    },
    "insurance": {
      "insuranceNumber": "1234512345",
      "validTill": "09-09-1234",
      "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
    },
    "_id": "6388c33fc6b2d524a07fdc15",
    "name": "Aidabeg",
    "phone": "+919999999999",
    "email": "aidabeg.khidirov@gmail.com",
    "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-image_picker649446327842398215.jpg",
    "role": "user",
    "firebaseUid": "UcN7eGb1oVShfCwm3Ogwry6q9T93",
    "firebaseSignInProvider": "phone",
    "gender": "male",
    "address": "Janakpuri Delhi",
    "suspensionReason": "user suspend",
    "isSuspended": false,
    "noOfRides": 26,
    "isDeleted": false,
    "createdAt": "2022-12-01T15:07:43.680Z",
    "updatedAt": "2023-10-19T06:28:00.336Z",
    "dob": "1995-05-26T00:00:00.000Z",
    "isApproved": true,
    "totalTravelKm": 0,
    "stripeCustomerId": "cus_NrUqU0rlJ0QffW",
    "stripeCardId": "card_1Nznd1ERG4ZXrlcJjitNdhT9",
    "stripeCards": [
      {
        "encryptedCode": "U2FsdGVkX1+W4TCBMcZNJC0Tk6R+kdN/x186dIePUxiu1KDtQCijARM8FPU6T+Bm4QEN/Wtc7l8hXs22busRnkvpQ1Xoc7wuRDwB0qhI+U1lCndFFnKMjLNbPNksLtP+q0Qv1jNIQFFt/UR9FBMlN7v7Tb4F9HRgUTfCjATvIEk=",
        "stripeCardId": "card_1N5lqvERG4ZXrlcJ1xsAzT9V",
        "_id": "645a035a49fea5271de9d913"
      }
    ],
    "isRejected": false
  },
  "car": {
    "position": {
      "type": "Point",
      "coordinates": [
        -121.382538
      ]
    },
    "_id": "63f377e5d6cc2f883de290ce",
    "brand": "Toyota",
    "model": "Prius",
    "qnr": "6DB9853D00FFF005",
    "seatCapacity": 5,
    "color": "White",
    "carType": "fuel",
    "images": [
      "https://zammadl.s3.us-west-1.amazonaws.com/zammadl-2021_toyota_prius_prime_angularfront.jpg"
    ],
    "isDamaged": false,
    "status": "active",
    "bookingStatus": "booked",
    "isDeleted": false,
    "createdAt": "2023-02-20T13:38:45.912Z",
    "updatedAt": "2023-10-19T06:47:33.379Z",
    "category": "sedan",
    "fuelType": "fuel",
    "bluetooth_connection": "disconnected",
    "board_voltage": 12.49,
    "ignition": "on",
    "immobilizer": "unlocked",
    "mileage": 28457,
    "mileage_since_immobilizer_unlock": 0,
    "alarm_input": "off",
    "alarm_input_2": "off",
    "low_battery_level_alarm": false,
    "low_fuel_level_alarm": true,
    "relay_value": 0,
    "qrCodeImage": "https://www.hellotech.com/guide/wp-content/uploads/2020/05/HelloTech-qr-code.jpg",
    "central_lock": "locked",
    "central_lock_last_command": "locked",
    "keyfob": "in",
    "vehicle_identification_number": "",
    "vehicle_license_plate": "",
    "isPaused": false,
    "speed": 0,
    "fuel_level": 21
  },
  "qnr": "6DB9853D00FFF005",
  "status": "ongoing",
  "pickupTime": "2023-10-19T06:33:42.000Z",
  "dropTime": "",
  "cancelReason": "",
  "cancelledBy": "",
  "isPaymentSuccess": false,
  "paymentMethod": "",
  "rideEndedBy": "user",
  "waitingTime": 339,
  "additionalWaitingTime": 0,
  "tripTime": 0,
  "path": [
    [
      "38.617905"
    ]
  ],
  "ridePauseTime": 0,
  "tripData": [
    {
      "qnr": "6DB9853D00FFF005",
      "reception_timestamp": "2023-10-19T06:33:44.510Z",
      "event": {
        "timestamp": "2023-10-19T06:33:42.000Z",
        "reasons": [
          "immobilizer_changed"
        ],
        "source": "server",
        "request_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
        "flow_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
        "status": {
          "fuel_level": 21,
          "mileage": 28457,
          "mileage_since_immobilizer_unlock": 1,
          "immobilizer": "unlocked",
          "ignition": "off",
          "central_lock": "locked",
          "keyfob": "in",
          "speed": 0,
          "bluetooth_connection": "disconnected",
          "board_voltage": 12.73,
          "seconds_since_immobilizer_unlock": 0,
          "central_lock_last_command": "locked",
          "alarm_input": "off",
          "alarm_input_2": "off",
          "alarm_inputs": {
            "1": "OFF",
            "2": "OFF"
          },
          "low_fuel_level_alarm": true,
          "low_battery_level_alarm": false,
          "relay_value": 0,
          "tilt_status": "unknown",
          "position": {
            "timestamp": "2023-10-19T06:32:22.000Z",
            "lon": -121.381905,
            "lat": 38.617905,
            "hdop": 0.65,
            "speed_over_ground": 0,
            "quality": 1,
            "satellites_in_use": 18,
            "altitude": 20,
            "heading": 161,
            "navigation_solution": "standalone_3d"
          },
          "bluetooth_authenticated": false
        }
      }
    }
  ],
  "isDeleted": false,
  "ignitionEvents": [
    {
      "status": "on",
      "time": "2023-10-19T06:45:22.000Z",
      "_id": "6530d0854beb27c50e37cbe3"
    }
  ],
  "createdAt": "2023-10-19T06:27:59.718Z",
  "updatedAt": "2023-10-19T06:47:33.790Z",
  "paymentStep": "initialPayment",
  "inspections": {
    "_id": "6530cdc34beb27c50e37cb34",
    "booking": "6530cc6f4beb27c50e37cb01",
    "carImagesBeforeRide": [
      {
        "respectiveSide": "Front Hood",
        "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
        "_id": "6530cdc34beb27c50e37cb35"
      }
    ],
    "carImagesAfterRide": [
      {
        "respectiveSide": "Front Hood",
        "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
        "_id": "6530cdc34beb27c50e37cb35"
      }
    ],
    "createdAt": "2023-10-19T06:33:39.048Z",
    "updatedAt": "2023-10-19T06:33:39.048Z"
  },
  "id": "6530cc6f4beb27c50e37cb01"
}
*/

  BookingDetailsModelsDataPickupLocation? pickupLocation;
  BookingDetailsModelsDataDropLocation? dropLocation;
  String? Id;
  BookingDetailsModelsDataUser? user;
  BookingDetailsModelsDataCar? car;
  String? qnr;
  String? status;
  String? pickupTime;
  String? dropTime;
  String? cancelReason;
  String? cancelledBy;
  bool? isPaymentSuccess;
  String? paymentMethod;
  String? rideEndedBy;
  int? waitingTime;
  int? additionalWaitingTime;
  int? tripTime;
  List<List<String?>?>? path;
  int? ridePauseTime;
  List<BookingDetailsModelsDataTripData?>? tripData;
  bool? isDeleted;
  List<BookingDetailsModelsDataIgnitionEvents?>? ignitionEvents;
  String? createdAt;
  String? updatedAt;
  String? paymentStep;
  BookingDetailsModelsDataInspections? inspections;
  String? id;

  BookingDetailsModelsData({
    this.pickupLocation,
    this.dropLocation,
    this.Id,
    this.user,
    this.car,
    this.qnr,
    this.status,
    this.pickupTime,
    this.dropTime,
    this.cancelReason,
    this.cancelledBy,
    this.isPaymentSuccess,
    this.paymentMethod,
    this.rideEndedBy,
    this.waitingTime,
    this.additionalWaitingTime,
    this.tripTime,
    this.path,
    this.ridePauseTime,
    this.tripData,
    this.isDeleted,
    this.ignitionEvents,
    this.createdAt,
    this.updatedAt,
    this.paymentStep,
    this.inspections,
    this.id,
  });
  BookingDetailsModelsData.fromJson(Map<String, dynamic> json) {
    pickupLocation = (json['pickupLocation'] != null) ? BookingDetailsModelsDataPickupLocation.fromJson(json['pickupLocation']) : null;
    dropLocation = (json['dropLocation'] != null) ? BookingDetailsModelsDataDropLocation.fromJson(json['dropLocation']) : null;
    Id = json['_id']?.toString();
    user = (json['user'] != null) ? BookingDetailsModelsDataUser.fromJson(json['user']) : null;
    car = (json['car'] != null) ? BookingDetailsModelsDataCar.fromJson(json['car']) : null;
    qnr = json['qnr']?.toString();
    status = json['status']?.toString();
    pickupTime = json['pickupTime']?.toString();
    dropTime = json['dropTime']?.toString();
    cancelReason = json['cancelReason']?.toString();
    cancelledBy = json['cancelledBy']?.toString();
    isPaymentSuccess = json['isPaymentSuccess'];
    paymentMethod = json['paymentMethod']?.toString();
    rideEndedBy = json['rideEndedBy']?.toString();
    waitingTime = json['waitingTime']?.toInt();
    additionalWaitingTime = json['additionalWaitingTime']?.toInt();
    tripTime = json['tripTime']?.toInt();
    if (json['path'] != null) {
      final v = json['path'];
      final arr0 = <List<String>>[];
      v.forEach((v) {
        final arr1 = <String>[];
        v.forEach((v) {
          arr1.add(v.toString());
        });
        arr0.add(arr1);
      });
      path = arr0;
    }
    ridePauseTime = json['ridePauseTime']?.toInt();
    if (json['tripData'] != null) {
      final v = json['tripData'];
      final arr0 = <BookingDetailsModelsDataTripData>[];
      v.forEach((v) {
        arr0.add(BookingDetailsModelsDataTripData.fromJson(v));
      });
      tripData = arr0;
    }
    isDeleted = json['isDeleted'];
    if (json['ignitionEvents'] != null) {
      final v = json['ignitionEvents'];
      final arr0 = <BookingDetailsModelsDataIgnitionEvents>[];
      v.forEach((v) {
        arr0.add(BookingDetailsModelsDataIgnitionEvents.fromJson(v));
      });
      ignitionEvents = arr0;
    }
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    paymentStep = json['paymentStep']?.toString();
    inspections = (json['inspections'] != null) ? BookingDetailsModelsDataInspections.fromJson(json['inspections']) : null;
    id = json['id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pickupLocation != null) {
      data['pickupLocation'] = pickupLocation!.toJson();
    }
    if (dropLocation != null) {
      data['dropLocation'] = dropLocation!.toJson();
    }
    data['_id'] = Id;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (car != null) {
      data['car'] = car!.toJson();
    }
    data['qnr'] = qnr;
    data['status'] = status;
    data['pickupTime'] = pickupTime;
    data['dropTime'] = dropTime;
    data['cancelReason'] = cancelReason;
    data['cancelledBy'] = cancelledBy;
    data['isPaymentSuccess'] = isPaymentSuccess;
    data['paymentMethod'] = paymentMethod;
    data['rideEndedBy'] = rideEndedBy;
    data['waitingTime'] = waitingTime;
    data['additionalWaitingTime'] = additionalWaitingTime;
    data['tripTime'] = tripTime;
    if (path != null) {
      final v = path;
      final arr0 = [];
      v!.forEach((v) {
        final arr1 = [];
        v!.forEach((v) {
          arr1.add(v);
        });
        arr0.add(arr1);
      });
      data['path'] = arr0;
    }
    data['ridePauseTime'] = ridePauseTime;
    if (tripData != null) {
      final v = tripData;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['tripData'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    if (ignitionEvents != null) {
      final v = ignitionEvents;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['ignitionEvents'] = arr0;
    }
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['paymentStep'] = paymentStep;
    if (inspections != null) {
      data['inspections'] = inspections!.toJson();
    }
    data['id'] = id;
    return data;
  }
}

class BookingDetailsModels {
/*
{
  "status": true,
  "message": "Get a booking.",
  "data": {
    "pickupLocation": {
      "address": "",
      "type": "Point",
      "coordinates": [
        -121.381905
      ]
    },
    "dropLocation": {
      "type": "Point",
      "coordinates": [
        -121.382538
      ],
      "address": ""
    },
    "_id": "6530cc6f4beb27c50e37cb01",
    "user": {
      "dl": {
        "licenceNumber": "1234567890",
        "validTill": "02-09-1995",
        "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
      },
      "insurance": {
        "insuranceNumber": "1234512345",
        "validTill": "09-09-1234",
        "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
      },
      "_id": "6388c33fc6b2d524a07fdc15",
      "name": "Aidabeg",
      "phone": "+919999999999",
      "email": "aidabeg.khidirov@gmail.com",
      "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-image_picker649446327842398215.jpg",
      "role": "user",
      "firebaseUid": "UcN7eGb1oVShfCwm3Ogwry6q9T93",
      "firebaseSignInProvider": "phone",
      "gender": "male",
      "address": "Janakpuri Delhi",
      "suspensionReason": "user suspend",
      "isSuspended": false,
      "noOfRides": 26,
      "isDeleted": false,
      "createdAt": "2022-12-01T15:07:43.680Z",
      "updatedAt": "2023-10-19T06:28:00.336Z",
      "dob": "1995-05-26T00:00:00.000Z",
      "isApproved": true,
      "totalTravelKm": 0,
      "stripeCustomerId": "cus_NrUqU0rlJ0QffW",
      "stripeCardId": "card_1Nznd1ERG4ZXrlcJjitNdhT9",
      "stripeCards": [
        {
          "encryptedCode": "U2FsdGVkX1+W4TCBMcZNJC0Tk6R+kdN/x186dIePUxiu1KDtQCijARM8FPU6T+Bm4QEN/Wtc7l8hXs22busRnkvpQ1Xoc7wuRDwB0qhI+U1lCndFFnKMjLNbPNksLtP+q0Qv1jNIQFFt/UR9FBMlN7v7Tb4F9HRgUTfCjATvIEk=",
          "stripeCardId": "card_1N5lqvERG4ZXrlcJ1xsAzT9V",
          "_id": "645a035a49fea5271de9d913"
        }
      ],
      "isRejected": false
    },
    "car": {
      "position": {
        "type": "Point",
        "coordinates": [
          -121.382538
        ]
      },
      "_id": "63f377e5d6cc2f883de290ce",
      "brand": "Toyota",
      "model": "Prius",
      "qnr": "6DB9853D00FFF005",
      "seatCapacity": 5,
      "color": "White",
      "carType": "fuel",
      "images": [
        "https://zammadl.s3.us-west-1.amazonaws.com/zammadl-2021_toyota_prius_prime_angularfront.jpg"
      ],
      "isDamaged": false,
      "status": "active",
      "bookingStatus": "booked",
      "isDeleted": false,
      "createdAt": "2023-02-20T13:38:45.912Z",
      "updatedAt": "2023-10-19T06:47:33.379Z",
      "category": "sedan",
      "fuelType": "fuel",
      "bluetooth_connection": "disconnected",
      "board_voltage": 12.49,
      "ignition": "on",
      "immobilizer": "unlocked",
      "mileage": 28457,
      "mileage_since_immobilizer_unlock": 0,
      "alarm_input": "off",
      "alarm_input_2": "off",
      "low_battery_level_alarm": false,
      "low_fuel_level_alarm": true,
      "relay_value": 0,
      "qrCodeImage": "https://www.hellotech.com/guide/wp-content/uploads/2020/05/HelloTech-qr-code.jpg",
      "central_lock": "locked",
      "central_lock_last_command": "locked",
      "keyfob": "in",
      "vehicle_identification_number": "",
      "vehicle_license_plate": "",
      "isPaused": false,
      "speed": 0,
      "fuel_level": 21
    },
    "qnr": "6DB9853D00FFF005",
    "status": "ongoing",
    "pickupTime": "2023-10-19T06:33:42.000Z",
    "dropTime": "",
    "cancelReason": "",
    "cancelledBy": "",
    "isPaymentSuccess": false,
    "paymentMethod": "",
    "rideEndedBy": "user",
    "waitingTime": 339,
    "additionalWaitingTime": 0,
    "tripTime": 0,
    "path": [
      [
        "38.617905"
      ]
    ],
    "ridePauseTime": 0,
    "tripData": [
      {
        "qnr": "6DB9853D00FFF005",
        "reception_timestamp": "2023-10-19T06:33:44.510Z",
        "event": {
          "timestamp": "2023-10-19T06:33:42.000Z",
          "reasons": [
            "immobilizer_changed"
          ],
          "source": "server",
          "request_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
          "flow_id": "bfbe2a8c-124e-402f-a5f8-7a0ed31b1386",
          "status": {
            "fuel_level": 21,
            "mileage": 28457,
            "mileage_since_immobilizer_unlock": 1,
            "immobilizer": "unlocked",
            "ignition": "off",
            "central_lock": "locked",
            "keyfob": "in",
            "speed": 0,
            "bluetooth_connection": "disconnected",
            "board_voltage": 12.73,
            "seconds_since_immobilizer_unlock": 0,
            "central_lock_last_command": "locked",
            "alarm_input": "off",
            "alarm_input_2": "off",
            "alarm_inputs": {
              "1": "OFF",
              "2": "OFF"
            },
            "low_fuel_level_alarm": true,
            "low_battery_level_alarm": false,
            "relay_value": 0,
            "tilt_status": "unknown",
            "position": {
              "timestamp": "2023-10-19T06:32:22.000Z",
              "lon": -121.381905,
              "lat": 38.617905,
              "hdop": 0.65,
              "speed_over_ground": 0,
              "quality": 1,
              "satellites_in_use": 18,
              "altitude": 20,
              "heading": 161,
              "navigation_solution": "standalone_3d"
            },
            "bluetooth_authenticated": false
          }
        }
      }
    ],
    "isDeleted": false,
    "ignitionEvents": [
      {
        "status": "on",
        "time": "2023-10-19T06:45:22.000Z",
        "_id": "6530d0854beb27c50e37cbe3"
      }
    ],
    "createdAt": "2023-10-19T06:27:59.718Z",
    "updatedAt": "2023-10-19T06:47:33.790Z",
    "paymentStep": "initialPayment",
    "inspections": {
      "_id": "6530cdc34beb27c50e37cb34",
      "booking": "6530cc6f4beb27c50e37cb01",
      "carImagesBeforeRide": [
        {
          "respectiveSide": "Front Hood",
          "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
          "_id": "6530cdc34beb27c50e37cb35"
        }
      ],
      "carImagesAfterRide": [
        {
          "respectiveSide": "Front Hood",
          "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-CAP702341614654282345.jpg",
          "_id": "6530cdc34beb27c50e37cb35"
        }
      ],
      "createdAt": "2023-10-19T06:33:39.048Z",
      "updatedAt": "2023-10-19T06:33:39.048Z"
    },
    "id": "6530cc6f4beb27c50e37cb01"
  }
}
*/

  bool? status;
  String? message;
  BookingDetailsModelsData? data;

  BookingDetailsModels({
    this.status,
    this.message,
    this.data,
  });
  BookingDetailsModels.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? BookingDetailsModelsData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
