///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ImageUpload {
/*
{
  "status": true,
  "message": "Files uploaded",
  "urls": [
    "https://mytestbuckettest.s3.us-east-2.amazonaws.com/zammadl-Screenshot%202023-01-04%20at%201.45.03%20PM.png"
  ]
}
*/

  bool? status;
  String? message;
  List<String?>? urls;

  ImageUpload({
    this.status,
    this.message,
    this.urls,
  });
  ImageUpload.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['urls'] != null) {
      final v = json['urls'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      urls = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (urls != null) {
      final v = urls;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['urls'] = arr0;
    }
    return data;
  }
}
