import 'package:zammacarsharing/app/modules/booking/controllers/booking_controller.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ImoblizerStatus {
/*
{
  "state": "locked"
}
*/

  String? state;

  ImoblizerStatus({
    this.state,
  });
  ImoblizerStatus.fromJson(Map<String, dynamic> json) {
    state = json['state']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['state'] = state;
    return data;
  }

  LockStatus get lockStatus {
    if (state == 'locked') {
      return LockStatus.locked;
    } else if (state == 'unlocked') {
      return LockStatus.unlocked;
    } else {
      return LockStatus.unknown;
    }
  }
}
