///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LockModel {
/*
{
  "state": "locked"
}
*/

  String? state;

  LockModel({
    this.state,
  });
  LockModel.fromJson(Map<String, dynamic> json) {
    state = json['state']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['state'] = state;
    return data;
  }
}
