///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class logedInDetailsUserInsurance {
/*
{
  "insuranceNumber": "1234512345",
  "validTill": "09-09-1234",
  "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
}
*/

  String? insuranceNumber;
  String? validTill;
  String? image;

  logedInDetailsUserInsurance({
    this.insuranceNumber,
    this.validTill,
    this.image,
  });
  logedInDetailsUserInsurance.fromJson(Map<String, dynamic> json) {
    insuranceNumber = json['insuranceNumber']?.toString();
    validTill = json['validTill']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['insuranceNumber'] = insuranceNumber;
    data['validTill'] = validTill;
    data['image'] = image;
    return data;
  }
}

class logedInDetailsUserDl {
/*
{
  "licenceNumber": "1234567890",
  "validTill": "02-09-1995",
  "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
}
*/

  String? licenceNumber;
  String? validTill;
  String? image;

  logedInDetailsUserDl({
    this.licenceNumber,
    this.validTill,
    this.image,
  });
  logedInDetailsUserDl.fromJson(Map<String, dynamic> json) {
    licenceNumber = json['licenceNumber']?.toString();
    validTill = json['validTill']?.toString();
    image = json['image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['licenceNumber'] = licenceNumber;
    data['validTill'] = validTill;
    data['image'] = image;
    return data;
  }
}

class logedInDetailsUser {
/*
{
  "dl": {
    "licenceNumber": "1234567890",
    "validTill": "02-09-1995",
    "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
  },
  "insurance": {
    "insuranceNumber": "1234512345",
    "validTill": "09-09-1234",
    "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
  },
  "_id": "6388c33fc6b2d524a07fdc15",
  "name": "pushpam kumar",
  "phone": "+919999999999",
  "email": "p@gmail.com",
  "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-image_picker6843117698426803098.jpg",
  "role": "user",
  "firebaseUid": "UcN7eGb1oVShfCwm3Ogwry6q9T93",
  "firebaseSignInProvider": "phone",
  "gender": "male",
  "address": "Janakpuri Delhi",
  "suspensionReason": "",
  "isSuspended": false,
  "noOfRides": 117,
  "isDeleted": false,
  "createdAt": "2022-12-01T15:07:43.680Z",
  "updatedAt": "2023-02-10T10:02:43.139Z",
  "dob": "1999-05-09T00:00:00.000Z",
  "isApproved": true,
  "totalTravelKm": 0
}
*/

  logedInDetailsUserDl? dl;
  logedInDetailsUserInsurance? insurance;
  String? Id;
  String? name;
  String? phone;
  String? email;
  String? image;
  String? role;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? gender;
  String? address;
  String? suspensionReason;
  bool? isSuspended;
  int? noOfRides;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  String? dob;
  bool? isApproved;
  int? totalTravelKm;

  logedInDetailsUser({
    this.dl,
    this.insurance,
    this.Id,
    this.name,
    this.phone,
    this.email,
    this.image,
    this.role,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.gender,
    this.address,
    this.suspensionReason,
    this.isSuspended,
    this.noOfRides,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.dob,
    this.isApproved,
    this.totalTravelKm,
  });
  logedInDetailsUser.fromJson(Map<String, dynamic> json) {
    dl = (json['dl'] != null) ? logedInDetailsUserDl.fromJson(json['dl']) : null;
    insurance = (json['insurance'] != null) ? logedInDetailsUserInsurance.fromJson(json['insurance']) : null;
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    role = json['role']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    gender = json['gender']?.toString();
    address = json['address']?.toString();
    suspensionReason = json['suspensionReason']?.toString();
    isSuspended = json['isSuspended'];
    noOfRides = json['noOfRides']?.toInt();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    dob = json['dob']?.toString();
    isApproved = json['isApproved'];
    totalTravelKm = json['totalTravelKm']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dl != null) {
      data['dl'] = dl!.toJson();
    }
    if (insurance != null) {
      data['insurance'] = insurance!.toJson();
    }
    data['_id'] = Id;
    data['name'] = name;
    data['phone'] = phone;
    data['email'] = email;
    data['image'] = image;
    data['role'] = role;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['gender'] = gender;
    data['address'] = address;
    data['suspensionReason'] = suspensionReason;
    data['isSuspended'] = isSuspended;
    data['noOfRides'] = noOfRides;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['dob'] = dob;
    data['isApproved'] = isApproved;
    data['totalTravelKm'] = totalTravelKm;
    return data;
  }
}

class logedInDetails {
/*
{
  "status": true,
  "message": "User details",
  "user": {
    "dl": {
      "licenceNumber": "1234567890",
      "validTill": "02-09-1995",
      "image": "https://www.shutterstock.com/image-vector/driver-license-male-photo-identification-260nw-1227173818.jpg"
    },
    "insurance": {
      "insuranceNumber": "1234512345",
      "validTill": "09-09-1234",
      "image": "https://miro.medium.com/max/1400/1*Lm9aFB_p9Bx8afzwx6KvlA.png"
    },
    "_id": "6388c33fc6b2d524a07fdc15",
    "name": "pushpam kumar",
    "phone": "+919999999999",
    "email": "p@gmail.com",
    "image": "https://zammauserprofile.s3.us-west-1.amazonaws.com/user-profile-image_picker6843117698426803098.jpg",
    "role": "user",
    "firebaseUid": "UcN7eGb1oVShfCwm3Ogwry6q9T93",
    "firebaseSignInProvider": "phone",
    "gender": "male",
    "address": "Janakpuri Delhi",
    "suspensionReason": "",
    "isSuspended": false,
    "noOfRides": 117,
    "isDeleted": false,
    "createdAt": "2022-12-01T15:07:43.680Z",
    "updatedAt": "2023-02-10T10:02:43.139Z",
    "dob": "1999-05-09T00:00:00.000Z",
    "isApproved": true,
    "totalTravelKm": 0
  }
}
*/

  bool? status;
  String? message;
  logedInDetailsUser? user;

  logedInDetails({
    this.status,
    this.message,
    this.user,
  });
  logedInDetails.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    user = (json['user'] != null) ? logedInDetailsUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
