///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ParkingCordinatesDataPolygons {
/*
{
  "type": "MultiPolygon",
  "coordinates": [
    [
      [
        [
          38.63939475530513
        ]
      ]
    ]
  ]
}
*/

  String? type;
  List<List<List<List<double>?>?>?>? coordinates;

  ParkingCordinatesDataPolygons({
    this.type,
    this.coordinates,
  });
  ParkingCordinatesDataPolygons.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    if (json['coordinates'] != null) {
      final v = json['coordinates'];
      final arr0 = <List<List<List<double>>>>[];
      v.forEach((v) {
        final arr1 = <List<List<double>>>[];
        v.forEach((v) {
          final arr2 = <List<double>>[];
          v.forEach((v) {
            final arr3 = <double>[];
            v.forEach((v) {
              arr3.add(v.toDouble());
            });
            arr2.add(arr3);
          });
          arr1.add(arr2);
        });
        arr0.add(arr1);
      });
      coordinates = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    if (coordinates != null) {
      final v = coordinates;
      final arr0 = [];
      v!.forEach((v) {
        final arr1 = [];
        v!.forEach((v) {
          final arr2 = [];
          v!.forEach((v) {
            final arr3 = [];
            v!.forEach((v) {
              arr3.add(v);
            });
            arr2.add(arr3);
          });
          arr1.add(arr2);
        });
        arr0.add(arr1);
      });
      data['coordinates'] = arr0;
    }
    return data;
  }
}

class ParkingCordinatesData {
/*
{
  "polygons": {
    "type": "MultiPolygon",
    "coordinates": [
      [
        [
          [
            38.63939475530513
          ]
        ]
      ]
    ]
  },
  "_id": "6437cd086570ae3ef9860456",
  "createdAt": "2023-04-13T09:36:08.094Z",
  "updatedAt": "2023-04-13T09:36:08.094Z"
}
*/

  ParkingCordinatesDataPolygons? polygons;
  String? Id;
  String? createdAt;
  String? updatedAt;

  ParkingCordinatesData({
    this.polygons,
    this.Id,
    this.createdAt,
    this.updatedAt,
  });
  ParkingCordinatesData.fromJson(Map<String, dynamic> json) {
    polygons = (json['polygons'] != null) ? ParkingCordinatesDataPolygons.fromJson(json['polygons']) : null;
    Id = json['_id']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (polygons != null) {
      data['polygons'] = polygons!.toJson();
    }
    data['_id'] = Id;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class ParkingCordinates {
/*
{
  "status": true,
  "message": "All zones.",
  "data": [
    {
      "polygons": {
        "type": "MultiPolygon",
        "coordinates": [
          [
            [
              [
                38.63939475530513
              ]
            ]
          ]
        ]
      },
      "_id": "6437cd086570ae3ef9860456",
      "createdAt": "2023-04-13T09:36:08.094Z",
      "updatedAt": "2023-04-13T09:36:08.094Z"
    }
  ]
}
*/

  bool? status;
  String? message;
  List<ParkingCordinatesData>? data;

  ParkingCordinates({
    this.status,
    this.message,
    this.data,
  });
  ParkingCordinates.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ParkingCordinatesData>[];
      v.forEach((v) {
        arr0.add(ParkingCordinatesData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
