///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class savedCardsModelCards {
/*
{
  "encryptedCode": "U2FsdGVkX18i9i4eEUGqzG/s9TgV7OpP6Bv36UALBrdIMyqySZQwQNapT+E0N+Kq94FEKfRH/EWzlVvcnJvaf8+EXwcRYhly9SlNkDQ0nMjQJRhZ4ygMf+cZIA7sbwYm",
  "stripeCardId": "card_1N3Yc0ERG4ZXrlcJHgsRWyto",
  "_id": "6451f699369df8b8d63ba7bc"
}
*/

  String? encryptedCode;
  String? stripeCardId;
  String? Id;

  savedCardsModelCards({
    this.encryptedCode,
    this.stripeCardId,
    this.Id,
  });
  savedCardsModelCards.fromJson(Map<String, dynamic> json) {
    encryptedCode = json['encryptedCode']?.toString();
    stripeCardId = json['stripeCardId']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['encryptedCode'] = encryptedCode;
    data['stripeCardId'] = stripeCardId;
    data['_id'] = Id;
    return data;
  }
}

class savedCardsModel {
/*
{
  "status": true,
  "cards": [
    {
      "encryptedCode": "U2FsdGVkX18i9i4eEUGqzG/s9TgV7OpP6Bv36UALBrdIMyqySZQwQNapT+E0N+Kq94FEKfRH/EWzlVvcnJvaf8+EXwcRYhly9SlNkDQ0nMjQJRhZ4ygMf+cZIA7sbwYm",
      "stripeCardId": "card_1N3Yc0ERG4ZXrlcJHgsRWyto",
      "_id": "6451f699369df8b8d63ba7bc"
    }
  ]
}
*/

  bool? status;
  List<savedCardsModelCards?>? cards;

  savedCardsModel({
    this.status,
    this.cards,
  });
  savedCardsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    if (json['cards'] != null) {
      final v = json['cards'];
      final arr0 = <savedCardsModelCards>[];
      v.forEach((v) {
        arr0.add(savedCardsModelCards.fromJson(v));
      });
      cards = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (cards != null) {
      final v = cards;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['cards'] = arr0;
    }
    return data;
  }
}
